name: main

on: [push, pull_request]

jobs:
  smith:
    # if: ! startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install smith toolchain
        run: |
          sudo add-apt-repository -y ppa:silnrsi/smith-py3
          sudo add-apt-repository -y ppa:sile-typesetter/sile
          sudo apt-get update -y -q
          sudo apt-get install sile luarocks libfont-ttf-scripts-perl grcompiler -y -qq
          pip3 install Brotli --user
          python3 -m pip install --upgrade "silfont[git] @ git+https://github.com/silnrsi/pysilfont.git@master" --user
          python3 -m pip install --upgrade "feaxlib @ git+https://github.com/silnrsi/feax.git@main" --user
          python3 -m pip install --upgrade "smith @ git+https://github.com/silnrsi/smith.git@master" --user
          sudo luarocks install fontproof
      - name: Run smith
        run: |
          smith configure
          smith build
          smith zip
          smith sile
      - name: Upload fonts
        uses: actions/upload-artifact@v4
        with:
          name: fonts
          path: |
            results/*.ttf
            *.txt
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: results/releases
      - name: Upload proofs
        uses: actions/upload-artifact@v4
        with:
          name: proofs
          path: results/tests/sile/*.pdf
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release delete dev -y --cleanup-tag || true;
          gh release create dev
          --title "Development ${{ github.ref }} Build ${{ github.ref_name }}"
          --generate-notes
          --prerelease
          results/releases/*
